config/routes.rb
#
# Redhopper - Kanban boards for Redmine, inspired by Jira Agile (formerly known as
# Greenhopper), but following its own path.
# Copyright (C) 2015-2017 infoPiiaf <contact@infopiiaf.fr>
#
# This file is part of Redhopper.
#
# Redhopper is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Redhopper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Redhopper.  If not, see <http://www.gnu.org/licenses/>.
#
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/projects/:project_id/issues/kanbans', :to => 'kanbans#index', :as => 'project_kanbans'

post '/redhopper_issues', :to => 'redhopper_issues#create', :as => 'create_redhopper_issue'
delete '/redhopper_issues', :to => 'redhopper_issues#delete', :as => 'delete_redhopper_issue'
post '/redhopper_issues/move', :to => 'redhopper_issues#move', :as => 'move_redhopper_issue'
post '/redhopper_issues/block', :to => 'redhopper_issues#block', :as => 'block_redhopper_issue'
delete '/redhopper_issues/block', :to => 'redhopper_issues#unblock', :as => 'unblock_redhopper_issue'

app/controllers/kanbans_controller.rb
#
# Redhopper - Kanban boards for Redmine, inspired by Jira Agile (formerly known as
# Greenhopper), but following its own path.
# Copyright (C) 2015-2017 infoPiiaf <contact@infopiiaf.fr>
#
# This file is part of Redhopper.
#
# Redhopper is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Redhopper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Redhopper.  If not, see <http://www.gnu.org/licenses/>.
#
class KanbansController < ApplicationController
  unloadable

  before_action :find_project_by_project_id, :authorize

  def index
    @kanban_board = KanbanBoard.new @project
    @can_unsort = Feature.enabled "move_back_to_unsorted"
    @hide_tracker = Feature.enabled "hide_tracker_name"
    @description_tooltip = Feature.enabled "display_description_tooltip"
  end

end

app/views/kanbans/_kanban.html.haml
-#
-# Redhopper - Kanban boards for Redmine, inspired by Jira Agile (formerly known as
-# Greenhopper), but following its own path.
-# Copyright (C) 2015-2017 infoPiiaf <contact@infopiiaf.fr>
-#
-# This file is part of Redhopper.
-#
-# Redhopper is free software: you can redistribute it and/or modify
-# it under the terms of the GNU Affero General Public License as
-# published by the Free Software Foundation, either version 3 of the
-# License, or (at your option) any later version.
-#
-# Redhopper is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU Affero General Public License for more details.
-#
-# You should have received a copy of the GNU Affero General Public License
-# along with Redhopper.  If not, see <http://www.gnu.org/licenses/>.
-#
- sortable = kanban.sortable?
- comments = kanban.comments
- issue = kanban.issue
- tracker_class = kanban.tracker_color
%li{id: "issue-#{issue.id}-kanban-#{kanban.id}", class: 'Kanban', draggable: sortable ? "true" : "false"}
	/
		Redmine needs a tr for its contextual menu.
		So here is the whole table package…
	%table
		%tbody
			%tr.hascontextmenu{class: [kanban.highlight_class, tracker_class]}
				%td
					%input{type: "checkbox", name: "ids[]", value: issue.id}
					.issue-id
						= issue.tracker.name unless @hide_tracker
						= "##{issue.id}"
					- if sortable
						.sortable
							- unless kanban_iteration.first?
								= link_to (tag :img, src: '/images/2uparrow.png', alt: t('.move2top_arrow')), move_redhopper_issue_path(id: kanban.id, target_id: first_kanban.id, insert: "before"), method: :post, title: t('.move2top')
								- previous_kanban = kanbans[kanban_iteration.index - 1]
								= link_to (tag :img, src: '/images/1uparrow.png', alt: t('.moveup_arrow')), move_redhopper_issue_path(id: kanban.id, target_id: previous_kanban.id, insert: "before"), method: :post, title: t('.moveup')
							- unless kanban_iteration.last?
								- next_kanban = kanbans[kanban_iteration.index + 1]
								= link_to (tag :img, src: '/images/1downarrow.png', alt: t('.moveup_arrow')), move_redhopper_issue_path(id: kanban.id, target_id: next_kanban.id, insert: "after"), method: :post, title: t('.movedown')
								= link_to (tag :img, src: '/images/2downarrow.png', alt: t('.move2bottom_arrow')), move_redhopper_issue_path(id: kanban.id, target_id: last_kanban.id, insert: "after"), method: :post, title: t('.move2bottom')
							- if @can_unsort
								= link_to (tag :img, src: '/images/bullet_diamond.png', alt: t('.goto_unsorted')), delete_redhopper_issue_path(id: kanban.id), method: :delete, title: t('.goto_unsorted')
					- else
						.unsortable
							= link_to t('.goto_sorted'), create_redhopper_issue_path(issue_id: issue.id), method: :post
					%p= link_to issue.subject, issue
					- if kanban.blocking_issue?
						- kanban.blocked_issues.each do |blocker|
							%p.icon.icon-exclamation.blocker
								= t('.blocks')
								= link_to("##{blocker.id}.", blocker, title: blocker.subject)
					- if kanban.blocked_with_issues?
						- kanban.blockers.each do |blocker|
							%p.icon.icon-exclamation.blocker
								= t('.blocked_by')
								= link_to("##{blocker.id}.", blocker, title: blocker.subject)
					- if kanban.blocked_with_comment?
						- if comment_to_show = comments.last
							%div.icon.icon-exclamation.blocker
								= t('.blocked_by')
								%div.tooltip{style: 'display:inline-block;'}
									= link_to t('.last_note'), issue_path(issue, anchor: "note-#{issue.journals.visible.count}")
									%span.tip
										= textilizable(comment_to_show.notes)
								= link_to t('.unblock'), unblock_redhopper_issue_path(id: kanban.id), method: :delete
					- elsif sortable && comments.count > 0
						= link_to block_redhopper_issue_path(id: kanban.id), method: :post, title: t('.block_with') + t('.last_note') do
							= tag :img, src: '/plugin_assets/redhopper/images/exclamation-disabled.png', alt: t('.block_with') + t('.last_note')
					- if due_delta = kanban.due_delta
						.issue-due-before{title: t(due_delta.title) ,class: due_delta.css_class}= due_delta.abs_value + t('.due_unit')
					.meta-data
						- unless (desc = issue.description).blank?
							- if @description_tooltip
								%div.tooltip{style: 'display:inline-block;'}
									= link_to '<span class="icon icon-issue"></span>'.html_safe, '#'
									%span.tip
										= textilizable(desc)
							- else
								%span.icon.icon-issue{title: t('.description')}
						- unless comments.empty?
							%span.icon.icon-comment{title: t('.notes_count')}= comments.count
						- unless issue.attachments.empty?
							%span.icon.icon-attachment{title: t('.attachments_count')}= issue.attachments.count
						- unless (assignee = issue.assigned_to).nil?
							%span.icon.icon-user{title: t('.assigned_user')}
								- if assignee.is_a?(Group)
									%span{title: assignee.name}= assignee.name
								- elsif Setting.gravatar_enabled?
									= avatar(assignee, title: assignee.name(:firstname_lastname))
								- else
									%span{title: assignee.name(:firstname_lastname)}= assignee.name
					%p= progress_bar(issue.done_ratio, :legend => "#{issue.done_ratio}%")

%hr{id: "kanban-#{kanban.id}-after", class: 'Column-dropzone'}

app/views/kanbans/index.haml
-#
-# Redhopper - Kanban boards for Redmine, inspired by Jira Agile (formerly known as
-# Greenhopper), but following its own path.
-# Copyright (C) 2015-2017 infoPiiaf <contact@infopiiaf.fr>
-#
-# This file is part of Redhopper.
-#
-# Redhopper is free software: you can redistribute it and/or modify
-# it under the terms of the GNU Affero General Public License as
-# published by the Free Software Foundation, either version 3 of the
-# License, or (at your option) any later version.
-#
-# Redhopper is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU Affero General Public License for more details.
-#
-# You should have received a copy of the GNU Affero General Public License
-# along with Redhopper.  If not, see <http://www.gnu.org/licenses/>.
-#
%h2 Kanbans

%form{data: {cm_url: issues_context_menu_path}}
	= hidden_field_tag 'back_url', url_for(:params => request.query_parameters)
	%ol.KanbanBoard
		- @kanban_board.columns.each do |column|
			%li.KanbanBoard-column.Column
				%h3
					= column.issue_status.name
					%small{title: t(".issues_count")} (#{column.work_in_progress})
				%h4
					= t(".sorted")
				%ol
					- if first_kanban = column.sorted_issues.first
						%hr{id: "kanban-#{first_kanban.id}-before", class:'Column-dropzone'}
					- last_kanban = column.sorted_issues.last
					= render partial: 'kanban', collection: column.sorted_issues, locals: { kanbans: column.sorted_issues, first_kanban: first_kanban, last_kanban: last_kanban }
				%h4
					= t(".unsorted")
				%ul
					= render partial: 'kanban', collection: column.unsorted_issues

- content_for :header_tags do
	= stylesheet_link_tag 'redhopper', :plugin => 'redhopper'
	= javascript_include_tag 'redhopper', :plugin => 'redhopper'

-# Behavior of `context_menu` changed in Redmine 3.4.0, see:
-# https://framagit.org/infopiiaf/redhopper/issues/25
- if method(:context_menu).arity == 0
	= context_menu
- else
	= context_menu issues_context_menu_path